name: Lumenium
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8052295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E4E5E7'
    - '#6A6B6D'
    - '#F50200'
    - '#18181A'
    - '#FC8187'
  brandStrength: 0.4129692
  lightness: 0.6340268
  saturation: 0.2350143
  rhythmicContrast: 0.7400967
purpose: []
